config/routes.rb
Openmicrosite::Application.routes.draw do

  # Home
  root :to => 'pages#preregistration'

  # Live Webinar
  #root :to => 'pages#live'

  # Authentication
  devise_for :admins
  devise_for :users

  # Static pages
  get 'home' => 'pages#archive'
  get 'live' => 'pages#live'
  get 'archive' => 'pages#archive'
  get 'holding' => 'pages#holding'
  get 'login' => 'pages#login'
  get 'evaluation' => 'pages#evaluation'
  get 'help' => 'pages#help'
  # get 'pi' => 'pages#pi'

  # Feedback/submissions
  match 'contact' => 'contact#new', :as => 'contact', :via => :get
  match 'contact' => 'contact#create', :as => 'contact', :via => :post
  match 'feedback' => 'feedback#new', :as => 'feedback', :via => :get
  match 'feedback' => 'feedback#create', :as => 'feedback', :via => :post
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  devise :database_authenticatable, :trackable, :timeoutable, :lockable  
  attr_accessible :email, :password, :password_confirmation
end

app/models/feedback.rb
class Feedback

  include ActiveModel::Validations
  include ActiveModel::Conversion
  extend ActiveModel::Naming

  attr_accessor :lecture, :relevance, :info_presented, :likelihood_change,
                :technical, :body, :comment

  validates :lecture, :relevance, :info_presented, :likelihood_change,
            :body, :technical, presence: true

  validates :lecture, :relevance, :info_presented, :likelihood_change,
            :body, :technical, presence: true

  def initialize(attributes = {})
    attributes.each do |name, value|
      send("#{name}=", value)
    end
  end

  def persisted?
    false
  end

end

app/models/message.rb
class Message

  include ActiveModel::Validations
  include ActiveModel::Conversion
  extend ActiveModel::Naming

  attr_accessor :name, :email, :body

  validates :body, :presence => true

  def initialize(attributes = {})
    attributes.each do |name, value|
      send("#{name}=", value)
    end
  end

  def persisted?
    false
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  attr_accessible :name, :email, :company, :job, :password,
                  :password_confirmation, :remember_me, :hcp, :nothcp, :reminder, :future

  INVALID_EMAILS = %w(virginmedia.com ee.co.uk plus.net aol.com aol.co.uk sky.com tiscali.co.uk btinternet.com gmail.com googlemail.com hotmail.co.uk hotmail.com live.co.uk yahoo.com yahoo.co.uk yahoo.gr yahoo.fr outlook.com outlook.co.uk icloud.com ymail.com mail.com bigstring.com talktalk.co.uk )
  validates_format_of :email,
                      :without => /#{INVALID_EMAILS.map{|a| Regexp.quote(a)}.join('|')}/,
                      :message => "Please register using your work email address."

  after_create :send_user_and_admin_notification

  def self.suitable_for_reminders
    where(reminder: true)
  end

  # Reminder emails

  def self.check_and_send_archive
    # should be sent on following dates
    # reminder_archive - sent nov 27th, jan 16, march 7
    date1 = Date.new(2014, 7, 23)
    date2 = Date.new(2014, 1, 14)
    date3 = Date.new(2014, 1, 14)

    # check if we are on one of the require days
    # send the email to the users who have opted in
    if date1.today? || date2.today? || date3.today?
      users = self.suitable_for_reminders
      users.each do |user|
        UserMailer.archive_email(user).deliver
      end
    end
  end

  # def self.check_and_send_evaluation
    # should be sent on following dates
    # reminder_evaluation - sent nov 28th, jan 17, march 8
    # date1 = Date.new(2013, 11, 28)
    # date2 = Date.new(2014, 1, 17)
    # date3 = Date.new(2014, 3, 8)

    # check if we are on one of the require days
    # send the email to the users who have opted in
    # if date1.today? || date2.today? || date3.today?
     # users = self.suitable_for_reminders
      #users.each do |user|
       # UserMailer.evaluation_email(user).deliver
      #end
    #end
  #end

  def self.check_and_send_one_day_reminders
    # should be sent on the following dates
    # reminder_one_day - sent on nov 25th, jan 14, march 5
    date1 = Date.new(2014, 7, 3)
    date2 = Date.new(2014, 1, 13)
    date3 = Date.new(2014, 3, 5)

    if date1.today? || date2.today? || date3.today?
      users = self.suitable_for_reminders
      users.each do |user|
        UserMailer.reminder_one_day(user).deliver
      end
    end

  end

  def self.check_and_send_two_week_reminders
    # should be sent on the following dates
    #reminder_two_weeks - sent on nov 12, jan 10th, feb 20th
    date1 = Date.new(2014, 6, 24)
    date2 = Date.new(2014, 1, 10)
    date3 = Date.new(2014, 2, 20)

    if date1.today? || date2.today? || date3.today?
      users = self.suitable_for_reminders
      users.each do |user|
        UserMailer.reminder_two_week(user).deliver
      end
    end

  end


  private

  	def send_user_and_admin_notification
      AdminMailer.registration_notification(self).deliver
      UserMailer.welcome(self).deliver
  	end
end


 # EXCLUSION_DOMAINS = %w[
 #   gmail.com
 #   yahoo.com
 #   yahoo.co.uk
  #  hotmail.com
  #  hotmail.co.uk
 #   googlemail.com
 #   live.co.uk
#]

#EXCLUSION_REGEXP = Regexp.new('(?:' + EXCLUSION_DOMAINS.collect { |d| Regexp.escape(d)

#validates :email,
#  :format => {
#    :with => VALID_EMAIL_REGEXP,
#    :without => EXCLUSION_REGEXP,
#    :message => "%{value} may not be used to register. Please use your work email address."
#}

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
 protect_from_forgery

  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end

  helper_method :resource, :resource_name, :devise_mapping
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController

  def new
    @message = Message.new
  end

  def create
    @user = current_user
    @message = Message.new(params[:message])

    if @message.valid?
      @success = true
      NotificationsMailer.new_message(@message, @user).deliver
      respond_to do |format|
        format.js
        format.html
      end

    else
      @success = false

      respond_to do |format|
        format.js
      end
    end
  end

end

app/controllers/feedback_controller.rb
class FeedbackController < ApplicationController

  def new
    @feedback = Feedback.new
  end

  def create
    @feedback = Feedback.new(params[:feedback])
    if @feedback.valid?
      NotificationsMailer.new_feedback(@feedback, current_user).deliver
      redirect_to(root_path, :notice => "Your feedback was successfully submitted.")
    else
      redirect_to(evaluation_path, :notice => "Please fill all fields.")
    end
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  # remove this before deploying to production
  # before_filter :authenticate

  def home
  end

  def live
    @message = Message.new
  end

  def live_jan_15
    @message = Message.new
  end
  
  def live_mar_6
    @message = Message.new
  end  

  def archive
  end

  def zinc
  end

  def pi
  end

  def preregistration
  end

  def evaluation
    @feedback = Feedback.new
  end

  #protected

  #  def authenticate
  #	  authenticate_or_request_with_http_basic do |username, password|
  #	  username == "admin" && password == "urology2014"
  #	 end
   # end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/feedback_helper.rb
module FeedbackHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/contact/create.js.erb
<% if @success  %>
// show an actual nice bootstrap alert
$('#form-success').slideDown().delay(3000).slideUp();
// reset the form
$('form#new_message')[0].reset();

<% else %>
// show an actual nice bootstrap alert
$('#form-error').slideDown().delay(3000).slideUp();

<% end %>

app/views/contact/new.html.erb
<%= simple_form_for :message, :url => contact_path do |form| %>
  <fieldset class="fields">
    <div class="field">
      <%= form.label :name %>
      <%= form.text_field :name %>
    </div>
    
    <div class="field">
      <%= form.label :body %>
      <%= form.text_area :body %>
    </div>
  </fieldset>
  
  <fieldset class="actions">
    <%= form.submit "Send" %>
  </fieldset>
<% end %>

app/views/feedback/create.js.erb
<% if @success  %>
  // show an actual nice bootstrap alert
  $('#form-success').slideDown().delay(3000).slideUp();
  // reset the form
  $('form#new_message')[0].reset();
<% else %>
  // show an actual nice bootstrap alert
  $('#form-error').slideDown().delay(3000).slideUp();
<% end %>

app/views/feedback/new.html.erb
<%= simple_form_for :feedback, :url => feedback_path do |form| %>
  <fieldset class="fields">
    <div class="field">
      <%= form.label :name %>
      <%= form.text_field :name %>
    </div>
    
    <div class="field">
      <%= form.label :body %>
      <%= form.text_area :body %>
    </div>
  </fieldset>
  
  <fieldset class="actions">
    <%= form.submit "Send" %>
  </fieldset>
<% end %>

app/views/layouts/_header.html.erb
<!-- Navigation -->
    <div class="navbar navbar-default navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <!-- <a class="navbar-brand"><img src="img/logo.png" alt="Astellas Urology"></a> -->
        </div>
        <% if user_signed_in? %>
        <div class="collapse navbar-collapse navbar-right navbar-ex1-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "Home", root_path %></li>
            <li><a href="https://s3.amazonaws.com/streamingwell/Vesomni+PI.pdf", target="_blank">Prescribing Information</a></li>
            <li><%= link_to "Help Centre", help_path %></li>
            <li><a href="mailto:astellasurology@succinctcomms.com">Contact Us</a> </li>
            <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
          </ul>
        </div><!--/.nav-collapse -->
        <% else %>
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Register", new_user_registration_path %></li>
            <li><%= link_to "Login", login_path %></li>
            <li><%= link_to "Help Centre", help_path %></li>
            <li><%= link_to 'Forgotten your password?', new_password_path(resource_name) %></li>
          </ul>
        </div><!--/.nav-collapse -->
        <% end %>
      </div>
    </div> <!-- / .navigation -->

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <%= content_tag(:div, msg, class: "alert alert-#{name}") %>
<% end %>

app/views/layouts/_preregistration.html.erb
<div class="jumbotron">
	<%= render 'layouts/title' %>			
	<div class="col-md-10 col-offset-1" align="center">
				<p style="color:#00365C; font-size: 18px;">Please select whether you would like to:</p>
				<%= link_to 'Register', new_user_registration_path, class: "btn btn-danger btn-large" %>
				<%= link_to 'Login', login_path, class: "btn btn-primary btn-large" %>
				<br />
				<p><small style="font-size: 12px;"><%= link_to "Having trouble logging in?", help_path %></small></p>
			</div>
		</div>
	</div>
	<br />
<br />
<div class="col-md-8 col-md-offset-1" style="margin-top: 375px;">

	<%= render 'layouts/prefooter' %>

</div>

app/views/pages/home-copy.html.erb
<% if user_signed_in? %>

    <div class="jumbotron" style="padding: 20px 72px 20px 68px;">
        <h1>Prostate Cancer Lunchtime Webinars</h1>
        <h4><i>A multidisciplinary approach to prostate cancer understanding and management</i></h4>
        <br>
        <h5>Please login on January 15, 2014 at 13:00 to watch</h5><h5>John Doe from Astellas present a live webinar entitled:</h5>
        <br>
        <h3><span style="color: #A72B4D">Webinar Title</span></h3>
    </div>

<% else %>

    <!-- flash_notice to show if form submission is unsuccessful -->
    <!-- <div class="alert alert-error" id="form-error" style="display: none;">
        <strong>Please fill in all fields and confirm that you are a healthcare professional. These webinars are intended for healthcare professionals only.</strong>
    </div> -->

<div class="jumbotron" style="padding: 20px 72px 20px 68px;">
     <%= render 'layouts/title' %>


  <br>
  <h4>To register for this webinar series please complete the following information:</h4>
<div class="login span6">

    <%= simple_form_for(resource, :as => resource_name, :url => registration_path(resource_name), html: { class: 'form-horizontal'}) do |f| %>

    <%= f.input :name, :autofocus => true %>
    <%= f.input :email, :autofocus => true, label: "Work Email"%>
    <%= f.input :company, :autofocus => true, label: "Place of Work" %>
    <%= f.input :job, :autofocus => true, label: "Job Title" %>
    <%= f.input :password %>
    <%= f.input :password_confirmation %>

        <div class="login span6 offset2">

        <h6>Please tick this box if you permit two reminder emails to be sent to you prior to each live webinar and also again once each webinar has been archived for viewing on the website.</h6>
            <%= f.input :reminder, :as => :boolean, :label => "Accept", :input_html => { :checked => "checked", class: 'left-aligned-checkbox' } %>

        <h6>Please tick this box if you are happy to be contacted by Astellas Oncology in the future.</h6>
            <%= f.input :future, :as => :boolean, :label => "Accept", :input_html => { :checked => "checked" } %>

        <br>
          <p>Are you a healthcare professional? Please select either yes or no:</p>

          <div class="marketing">
            <%= f.button :submit, "Yes", class: 'btn btn-primary btn-large' %>
            <!-- Button trigger modal -->
            <a data-toggle="modal" href="#myModal" class="btn btn-danger btn-large">No</a>
          </div>

          <br>
  <!-- Modal -->
  <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-body">
          <h4><span style="color: rgb(167, 43, 77)">Unfortunately as you are not a healthcare professional you are not permitted to view these webinars.</span></h4>
        </div>
        <div class="modal-footer">
          <%= link_to "Please click here to close the web page", "http://astellas.eu", class: 'btn btn-primary btn-large' %>
        </div>
      </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
  </div><!-- /.modal -->
        </div>

<% end %>
</div>
    <div class= "bird">
        <img src="assets/bird_oncology.png"/>
    </div>
</div>
<% end %>

app/views/pages/home.html.erb
<% if user_signed_in? %>

<div class="jumbotron" style="padding: 20px 72px 20px 68px;">
  <%= render 'layouts/title' %>
  <br>
  <br>

<div class="span8 offset1">
<div class="accordion" id="accordion2">
  <div class="accordion-group">
    <div class="accordion-heading">
      <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapseOne">
        <h5><span style="color: #A72B4D">Working together: organising care <br>for optimal management of prostate cancer*</span></h5>

         <h6><strong><span style="color: #939598">
          Dr  Hughes, Consultant in Clinical Oncology and <br>Ms Louisa Fleure, Advanced Prostate Cancer Specialist Nurse, Guy's Hospital, London
        </span></strong></h6>

        <h6><span style="color: #A72B4D">Tuesday 26<sup>th</sup> November 2013 at 12.30-13.15</span></h6>

      </a>
              <i>*This session will include a discussion regarding the enzalutamide clinical data.</i>

    </div>
    <div id="collapseOne" class="accordion-body collapse in">
      <div class="accordion-inner">

            <!-- <iframe src="//player.vimeo.com/video" width="640" height="360" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe> -->
            <!-- <img src="assets/archived-webcast.png"/> -->
            <!-- <%= link_to "Leave Feedback", evaluation_path, class: "btn btn-danger" %> -->

            <br>
          <div class="row">
            <div class="span2">
              <br>
              <img src="assets/dr-simon-hughes.jpg" class="img-polaroid-orange">
              <h4>Dr Simon Hughes</h4>
              <img src="assets/louisa-fleure.jpg" class="img-polaroid-orange">

            </div>

            <div class="next-webinar span5">

              <p><strong>Summary:</strong></p>
              <p>Dr Simon Hughes and Ms Louisa Fleure will provide expert first-hand insights regarding the successful management of patients with prostate cancer in a multidisciplinary team (MDT) setup.</p>
                <br>
                  <p><strong>Topics:</strong></p>
                  <p><span style="color: #939598"><li>The multidisciplinary team (MDT) structure and roles</li></span></p>

                  <p><li>Managing patients with differing needs in an MDT environment</li></p>

                  <p><ul><li>Newly diagnosed patients</li></p>

                  <p><li>Patients with advanced disease</li></ul></p>

                  <p><li>Meeting the challenges of a ‘working’ MDT at Guy’s Hospital</li></p>

                </div>

              </div>
          </br>
          <br>
      </div>
    </div>
  </div>

<hr>

<br>

  <div class="accordion-group">
    <div class="accordion-heading">
      <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapseTwo">
        <h5><span style="color: #A72B4D">Maximising quality of life for patients <br>with advanced prostate cancer*</span></h5>

        <h6><strong><span style="color: #939598">
             Mr Lawrence Drudge-Coates, Uro-Oncology Clinical Nurse Specialist <br>and Honorary Lecturer King’s College Hospital NHS Foundation Trust, London
        </span></strong></h6>

        <h6><span style="color: #A72B4D">Wednesday 15<sup>th</sup> January 2014 at 12.30-13.15</span></h6>
      </a>
        <i>*This session will include a discussion regarding the enzalutamide clinical data.</i>
    </div>
    <div id="collapseTwo" class="accordion-body collapse">
      <div class="accordion-inner">

           <!-- <iframe src="//player.vimeo.com/video" width="640" height="360" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe> -->
            <!-- <img src="assets/archived-webcast.png"/> -->
            <!-- <%= link_to "Leave Feedback", evaluation_path, class: "btn btn-danger" %> -->


          <div class="row">
            <div class="span2">
              <br>
              <img src="assets/lawrence-druge-coates.jpg" class="img-polaroid">
            </div>

            <div class="next-webinar span5">
          <p><strong>Summary:</strong></p>
          <p>Mr Lawrence Drudge-Coates will discuss how balancing quantity and quality of life is a key factor in a patient’s choice of treatment, particularly as the number of treatment options is increasing significantly both in quantity and complexity.</p>
            <br>
              <p><strong>Topics:</strong></p>
              <p><li>Impact on quality of life of treatments used in advanced prostate cancer</li></p>

              <p><li> Management of side-effects of treatments used in advanced prostate cancer</li></p>

              <p><li>Helping patients balance quality and quantity of life</li></p>

            </div>

          </br>

          <br>
      </div>
    </div>
  </div>

<hr>
<br>

  <div class="accordion-group">
    <div class="accordion-heading">
      <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapseThree">
        <h5><span style="color: #A72B4D">Androgens and prostate cancer: <br>source, role and management*</span></h5>

        <h6><strong><span style="color: #939598">
             Dr Amit Bahl, Clinical Director and Consultant Oncologist <br>Bristol Haematology and Oncology Centre, University Hospitals Bristol
        </span></strong></h6>

          <h6><span style="color: #A72B4D">Thursday 6<sup>th</sup> March 2014 at 12.30-13.15</span></h6>
      </a>
      <i>*This session will include a discussion regarding the enzalutamide clinical data.</i>
    </div>
    <br>
    <div id="collapseThree" class="accordion-body collapse">
      <div class="accordion-inner">

       <!-- <iframe src="//player.vimeo.com/video" width="640" height="360" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe> -->
            <!-- <img src="assets/archived-webcast.png"/> -->
            <!-- <%= link_to "Leave Feedback", evaluation_path, class: "btn btn-danger" %> -->


        <div class="row">
          <div class="span2">
            <br>
            <img src="assets/amit-bahl.jpg" class="img-polaroid">
        </div>

        <div class="next-webinar span5">
          <p><strong>Summary:</strong></p>
          <p>Dr Amit Bahl will provide an overview of the role of androgens in prostate cancer and how different treatment options, old and new, can modulate the production or action of androgens and reduce the progression of disease.</p>
            <br>
              <p><strong>Topics:</strong></p>
              <p><li>Sites of androgen production and its effect on prostate cancer</li></p>

              <p><li>Treatments that affect androgen production or action</li></p>

              <p><li> Enzalutamide clinical trial data and clinical experience</li></p>

            </div>
      </div>
    </div>
  </div>

</div>
</div>
</div>

<% else %>

    <!-- flash_notice to show if form submission is unsuccessful -->
    <!-- <div class="alert alert-error" id="form-error" style="display: none;">
        <strong>Please fill in all fields and confirm that you are a healthcare professional. These webinars are intended for healthcare professionals only.</strong>
    </div> -->

<div class="jumbotron">
  <%= render 'layouts/title' %>
  <br>
  <br>
    <h4>To register for this webinar series please complete the following information:</h4>
  
  <div class="col-sm-6 col-sm-offset-3 well">

    <%= simple_form_for(resource, :as => resource_name, :url => registration_path(resource_name), html: { class: 'form-horizontal'}) do |f| %>

    <%= f.input :name, :autofocus => true, label: "Name:" %>
    <%= f.input :email, :autofocus => true, label: "Work email address:"%>
    <%= f.input :company, :autofocus => true, label: "Place of work:" %>
    <%= f.input :job, :autofocus => true, label: "Job title:" %>
    <%= f.input :password, label: "Password:" %>
    <%= f.input :password_confirmation, label: "Password confirmation:" %>

        <div class="login span6 offset2">

        <h6>Please tick this box if you permit Astellas Oncology to send you two reminder emails prior to each live webinar, an email when each webinar is archived for viewing on the website and an email when a new webinar is added to the programme.</h6>
            <%= f.input :reminder, :as => :boolean, :label => "Please tick this box if you permit Astellas Oncology to send you two reminder emails prior to each live webinar, an email when each webinar is archived for viewing on the website and an email when a new webinar is added the programme.", :input_html => { :checked => "checked", class: 'left-aligned-checkbox' } %>

        <h6>Please tick this box if you permit Astellas Oncology to contact you in the future regarding other similar activities.</h6>
            <%= f.input :future, :as => :boolean, :label => "Accept", :input_html => { :checked => "checked" } %>

        <br>

        <p>Once you have registered, a confirmation email will be sent to you.</p>

        <br>
          <p>Are you a healthcare professional? Please select either yes or no:</p>

          <div class="marketing">
            <%= f.button :submit, "Yes", class: 'btn btn-primary btn-large' %>
            <!-- Button trigger modal -->
            <a data-toggle="modal" href="#myModal" class="btn btn-danger btn-large">No</a>
          </div>

          <br></br>
  <!-- Modal -->
  <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" data-keyboard="false" data-backdrop="static">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-body">
          <h4>Unfortunately as you are not a healthcare professional you are not permitted to view these webinars.</h4>
        </div>
        <div class="modal-footer">
          <%= link_to "Please click here to close the web page", "http://astellas.eu", class: 'btn btn-primary btn-large' %>
        </div>
      </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
  </div><!-- /.modal -->
        </div>

<% end %>
</div>

</div>
<% end %>

app/views/pages/home_copy.html.erb
<% if user_signed_in? %>

    <div class="jumbotron" style="padding: 20px 72px 20px 68px;">
        <h1>Prostate Cancer Lunchtime Webinars</h1>
        <h4><i>A multidisciplinary approach to prostate cancer understanding and management</i></h4>
        <br>
        <h5>Please login on January 15, 2014 at 13:00 to watch</h5><h5>John Doe from Astellas present a live webinar entitled:</h5>
        <br>
        <h3><span style="color: #A72B4D">Webinar Title</span></h3>
    </div>

<% else %>

    <!-- flash_notice to show if form submission is unsuccessful -->
    <!-- <div class="alert alert-error" id="form-error" style="display: none;">
        <strong>Please fill in all fields and confirm that you are a healthcare professional. These webinars are intended for healthcare professionals only.</strong>
    </div> -->

<div class="jumbotron" style="padding: 20px 72px 20px 68px;">
     <%= render 'layouts/title' %>


  <br>
  <h4>To register for this webinar series please complete the following information:</h4>
<div class="login span6">

    <%= simple_form_for(resource, :as => resource_name, :url => registration_path(resource_name), html: { class: 'form-horizontal'}) do |f| %>

    <%= f.input :name, :autofocus => true %>
    <%= f.input :email, :autofocus => true, label: "Work Email"%>
    <%= f.input :company, :autofocus => true, label: "Place of Work" %>
    <%= f.input :job, :autofocus => true, label: "Job Title" %>
    <%= f.input :password %>
    <%= f.input :password_confirmation %>

        <div class="login span6 offset2">

        <h6>Please tick this box if you permit two reminder emails to be sent to you prior to each live webinar and also again once each webinar has been archived for viewing on the website.</h6>
            <%= f.input :reminder, :as => :boolean, :label => "Accept", :input_html => { :checked => "checked", class: 'left-aligned-checkbox' } %>

        <h6>Please tick this box if you are happy to be contacted by Astellas Oncology in the future.</h6>
            <%= f.input :future, :as => :boolean, :label => "Accept", :input_html => { :checked => "checked" } %>

        <br>
          <p>Are you a healthcare professional? Please select either yes or no:</p>

          <div class="marketing">
            <%= f.button :submit, "Yes", class: 'btn btn-primary btn-large' %>
            <!-- Button trigger modal -->
            <a data-toggle="modal" href="#myModal" class="btn btn-danger btn-large">No</a>
          </div>

          <br>
  <!-- Modal -->
  <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-body">
          <h4><span style="color: rgb(167, 43, 77)">Unfortunately as you are not a healthcare professional you are not permitted to view these webinars.</span></h4>
        </div>
        <div class="modal-footer">
          <%= link_to "Please click here to close the web page", "http://astellas.eu", class: 'btn btn-primary btn-large' %>
        </div>
      </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
  </div><!-- /.modal -->
        </div>

<% end %>
</div>
    <div class= "bird">
        <img src="assets/bird_oncology.png"/>
    </div>
</div>
<% end %>